// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/tikivn/clickhousectl/internal/app/cli"
	"github.com/tikivn/clickhousectl/internal/pkg/api"
	"github.com/tikivn/clickhousectl/internal/pkg/infra"
	"github.com/tikivn/clickhousectl/internal/pkg/repo/mysql"
	"github.com/tikivn/clickhousectl/internal/pkg/service"
	"github.com/tikivn/clickhousectl/internal/setting"
)

// Injectors from wire.go:

func initGoApp(ctx context.Context) (cli.App, func(), error) {
	mySql := setting.NewMySqlConfig()
	db, cleanup, err := infra.NewMySqlSession(mySql)
	if err != nil {
		return nil, nil, err
	}
	userRepo := mysql.NewUserRepo(db)
	clickHouseServerRepo := mysql.NewClickHouseServerRepo(db, userRepo)
	tableOperatorService := service.NewTableOperatorService(clickHouseServerRepo)
	tableHandler := api.NewTableHandler(tableOperatorService)
	columnOperatorService := service.NewColumnOperatorService(clickHouseServerRepo)
	columnHandler := api.NewColumnHandler(columnOperatorService)
	httpServer := cli.NewHttpServer(tableHandler, columnHandler)
	app := cli.NewApp(httpServer)
	return app, func() {
		cleanup()
	}, nil
}
